
project_id = "zdpwgoiisigyuiudlbzz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = false

[functions.schedule-cricket-updates]
verify_jwt = false

[functions.auto-fetch-cricket-data]
verify_jwt = false
