// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdpwgoiisigyuiudlbzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcHdnb2lpc2lneXVpdWRsYnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTIyOTUsImV4cCI6MjA2MDcyODI5NX0.rf2iB5zO2qR_7cus3WveyqcF-_eVG_4_MLzIB-V89oY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);